CrashTerminal:

  #How fast the minecart needs to move before triggering a crash on impact (Type an integer between 0 and 1)
  Velocity: 0.1

  #On impact, there will be explosions nearby. What should the radius be? (Type an integer. Measured in blocks.)
  RandomRadius: 6

  #On impact, how strong should be the explosions be? (Type an integer, followed by "F".
  #For example, 8F.
  RandomStrength: 12F

  #After the initial blast, how many explosions should occur randomly? (Type an integer)
  RandomAmount: 4

#Should the initial blast destroy blocks? (Type a boolean. Cannot be null.)
initial-break-blocks: false

#Should the following random blasts destroy blocks? (Type a boolean. Cannot be null.)
random-break-blocks: true